export const navLinksEn = [
    {
        id:1,
        text:'Home',
        url:'home',
    },
    {
        id:2,
        text:'About',
        url:'about',
    },
    {
        id:3,
        text:'Skills',
        url:'skills',
    },
    {
        id:4,
        text:'Work',
        url:'work',
    },
    {
        id:5,
        text:'Contact',
        url:'contact',
    }
]

export const navLinksDe = [
    {
        id:1,
        text:'Zuhause',
        url:'home',
    },
    {
        id:2,
        text:'Über mich',
        url:'about',
    },
    {
        id:3,
        text:'Fähigkeiten',
        url:'skills',
    },
    {
        id:4,
        text:'Projekte',
        url:'work',
    },
    {
        id:5,
        text:'Kontakt',
        url:'contact',
    }
]